### ISSUE TITLE
Windows -- Door Entry Sample Reports Error -- Referencing a Linux directory

### ISSUE THREAD

**Issue by mmwilder26** [rkvst/rkvst-samples#74]
**Describe the bug**
When executing the door entry list all sample on Windows an error is reported: FileNotFoundError: 'tmp/xxx'

**To Reproduce**
1. Execute door entry list all sample per rkvst-samples main readme
2. Begins to execute and then an error is reported. . . see below 

*************
PS C:\Users\north\AppData\Roaming\Python\Python311\Scripts> python archivist_samples_door_entry.exe -u $Env:TEST_ARCHIVIST -t $Env:TEST_AUTHTOKEN --namespace $Env:NAMESPACE --list all
Initialising connection to RKVST...
Using version v0.23.0 of rkvst-archivist
Fetching use case test assets namespace 1687345330.72348
number of doors 6
number of cards 5
List all START
Listing all doors tracked by the system:
       Asset name:    Gare du Nord apartments side door
       Asset type:    Door access terminal
       Asset location: Apartements du Gare du Nord
       Asset address: 18 Rue de Dunkerque, 75010 Paris, France
       Archivist ID:  assets/cc728cb7-0d59-4aef-a738-6fe96178bcce
       Attachment identity:   blobs/5d13e759-c5bc-4dcc-b67b-dffa5258bb69
       Attachment name:       None
Traceback (most recent call last):
 File "<frozen runpy>", line 198, in _run_module_as_main
 File "<frozen runpy>", line 88, in _run_code
 File "C:\Users\north\AppData\Roaming\Python\Python311\Scripts\archivist_samples_door_entry.exe\__main__.py", line 7, in <module>
 File "C:\Users\north\AppData\Roaming\Python\Python311\site-packages\archivist_samples\door_entry\main.py", line 72, in main
   run(arch, args)
 File "C:\Users\north\AppData\Roaming\Python\Python311\site-packages\archivist_samples\door_entry\run.py", line 623, in run
   list_doors(doors)
 File "C:\Users\north\AppData\Roaming\Python\Python311\site-packages\archivist_samples\door_entry\run.py", line 328, in list_doors
   with open("/tmp/xxx", "wb") as fd:
        ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/xxx'
*****************

**Expected behavior**
For the door entry list all sample to successfully execute on Windows

**Desktop (please complete the following information):**
 - OS: [Windows]

This was reported by @pcnorth  . . . please feel free to reach out to him directly for additional information (versions, etc. . .)

**Comment by eccles** [comment]
https://stackoverflow.com/questions/847850/cross-platform-way-of-getting-temp-directory-in-python

is pertinent. The code is explicitly written for Linux so some work must be done to use the tempfile module instead.
